
name: 'dbt_enablement'
version: '1.2.0'
config-version: 2

profile: 'bdc-dbt-enablement'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_enablement:
      +materialized: view
